const data = {
  products: [
    {
      name: 'Dog',
      slug: 'Dog',
      category: 'Toys',
      image: '/images/p1.jpg', // 500 x 500
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Cat',
      slug: 'Cat',
      category: 'Toys',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Bird',
      slug: 'Bird',
      category: 'Toys',
      image: '/images/p3.jpg',
      price: 500,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Fish',
      slug: 'Fish',
      category: 'Toys',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Bear',
      slug: 'Bear',
      category: 'Toys',
      image: '/images/p5.jpg',
      price: 300,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Lion',
      slug: 'Lion',
      category: 'Toys',
      image: '/images/p6.jpg',
      price: 300,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Elephant',
      slug: 'Elephant',
      category: 'Toys',
      image: '/images/p7.jpg',
      price: 300,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Monkey',
      slug: 'Monkey',
      category: 'Toys',
      image: '/images/p8.jpg',
      price: 300,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
  ],
};
export default data;
